In [2]:
max([1])

1

In [15]:
from collections import Counter

tokens = 'hello hello hi'.split(' ')
tokens2 = 'bye'.split(' ')
counter = Counter(tokens)
counter2 = Counter(tokens2)

print(counter)
print(counter2)

counter.subtract(counter2)
print(counter)


Counter({'hello': 2, 'hi': 1})
Counter({'bye': 1})
Counter({'hello': 2, 'hi': 1, 'bye': -1})


In [17]:
import torch
a = torch.FloatTensor([[1, 2], [3, 4]])

a.softmax(dim=1)

tensor([[0.2689, 0.7311],
        [0.2689, 0.7311]])

In [29]:
import torch.nn.functional as F

idx = torch.zeros([1, 2], dtype=torch.long)
idx[0, 0] = 1
idx[0, 1] = 2
print(idx)

a = F.one_hot(idx, num_classes = 10)
print(a)
print(a.shape)

tensor([[1, 2]])
tensor([[[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]]])
torch.Size([1, 2, 10])


In [24]:
import json
from torchtext.data import get_tokenizer
from tqdm import tqdm

with open("../torch_datasets/annotations/captions_val2014.json", "r") as f:
    annotaion = json.load(f)

tokenizer = get_tokenizer("basic_english")
max_cap_len = 0
for i in tqdm(range(420000)):
    try:
        caption = annotaion['annotations'][i]['caption']
        tokens = tokenizer(caption)
        cap_len = len(tokens)
        max_cap_len = max_cap_len if max_cap_len > cap_len else cap_len
    except:
        break

print(max_cap_len)
# max_cap_len is 57!! (train 57, val 56)

 48%|████▊     | 202654/420000 [00:01<00:01, 143006.63it/s]

56


In [8]:
import torchvision.datasets as datasets
import torchvision.transforms as transforms

from tqdm import tqdm

# prepare datasets
train_dataset = datasets.CocoCaptions(
    root="../torch_datasets/train2014",
    annFile="../torch_datasets/annotations/captions_train2014.json",
    transform=transforms.ToTensor(),
)
val_dataset = datasets.CocoCaptions(
    root="../torch_datasets/val2014",
    annFile="../torch_datasets/annotations/captions_val2014.json",
    transform=transforms.ToTensor(),
)

max_cpi = 0
for i, (img, captions) in enumerate(tqdm(train_dataset)):
    cpi = len(captions)
    max_cpi = cpi if cpi > max_cpi else max_cpi

print(max_cpi) # max_cpi = 7

loading annotations into memory...
Done (t=0.35s)
creating index...
index created!
loading annotations into memory...
Done (t=0.18s)
creating index...
index created!


100%|██████████| 82783/82783 [10:26<00:00, 132.11it/s]

7


In [1]:
import torchvision.datasets as datasets
import torchvision.transforms as transforms

train_dataset = datasets.CocoCaptions(
    root="../torch_datasets/train2014",
    annFile="../torch_datasets/annotations/captions_train2014.json",
    transform=transforms.ToTensor(),
)

train_dataset.test_attribute = 'hello'
train_dataset.eka = "mother fucker"

print(train_dataset)
print(train_dataset.test_attribute)
print(train_dataset.eka)

/home/kookies371/miniconda3/envs/torch/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


loading annotations into memory...
Done (t=0.37s)
creating index...
index created!
Dataset CocoCaptions
    Number of datapoints: 82783
    Root location: ../torch_datasets/train2014
    StandardTransform
Transform: ToTensor()
hello
mother fucker


In [4]:
class AAA():
    def __init__(self):
        self.a = 'a'
        self.b = 'b'

aaa = AAA()
print(aaa.a)
print(aaa.b)

aaa.c = 'c'
print(aaa.c)

a
b
c


In [4]:
from dataset import CustomCOCOCaption
import torchvision.transforms as transforms

ds = CustomCOCOCaption(    
    root="../torch_datasets/train2014",
    annFile="../torch_datasets/annotations/captions_train2014.json",
    transform=transforms.ToTensor(),
    max_cpi = 100,
    max_cap_len = 100,
)

for i, (img, captions) in enumerate(ds):
    print(captions)

    if i == 3:
        break

loading annotations into memory...
Done (t=0.35s)
creating index...
index created!
['Closeup of bins of food that include broccoli and bread.', 'A meal is presented in brightly colored plastic trays.', 'there are containers filled with different kinds of foods', 'Colorful dishes holding meat, vegetables, fruit, and bread.', 'A bunch of trays that have different food.']
['A giraffe eating food from the top of the tree.', 'A giraffe standing up nearby a tree ', 'A giraffe mother with its baby in the forest.', 'Two giraffes standing in a tree filled area.', 'A giraffe standing next to a forest filled with trees.']
['A flower vase is sitting on a porch stand.', 'White vase with different colored flowers sitting inside of it. ', 'a white vase with many flowers on a stage', 'A white vase filled with different colored flowers.', 'A vase with red and white flowers outside on a sunny day.']
['A zebra grazing on lush green grass in a field.', 'Zebra reaching its head down to ground where grass i

In [24]:
from dataset import CustomCOCOCaption
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms
import torch

def collate_fn(x):
    # x = [(img, captions), ...]
    imgs, captionss = [], []
    for img, captions in x:
        imgs.append(img)
        captionss.append(captions)

    imgs = torch.stack(imgs, dim=0)
    return (imgs, captionss)


train_dataset = CustomCOCOCaption(
    root="../torch_datasets/train2014",
    annFile="../torch_datasets/annotations/captions_train2014.json",
    transform=transforms.Compose([
        transforms.ToTensor(),
        transforms.Resize((640, 640)),
    ]),
)

train_dataloader = DataLoader(
    train_dataset,
    batch_size=16,
    collate_fn=collate_fn,
)


for i, data in enumerate(train_dataloader):
    print(len(data[1][0]))

    break

loading annotations into memory...
Done (t=0.40s)
creating index...
index created!
5


In [25]:
from dataset import CustomCOCOCaption

train_dataset = CustomCOCOCaption(
    root="../torch_datasets/train2014",
    annFile="../torch_datasets/annotations/captions_train2014.json",
    transform=transforms.Compose([
        transforms.ToTensor(),
    ]),
)

for i, (img, captions) in enumerate(train_dataset):
    print(img.shape)

    if i == 30:
        break

loading annotations into memory...
Done (t=0.42s)
creating index...
index created!
torch.Size([3, 480, 640])
torch.Size([3, 426, 640])
torch.Size([3, 428, 640])
torch.Size([3, 425, 640])
torch.Size([3, 640, 481])
torch.Size([3, 500, 381])
torch.Size([3, 488, 640])
torch.Size([3, 640, 480])
torch.Size([3, 426, 640])
torch.Size([3, 640, 427])
torch.Size([3, 375, 500])
torch.Size([3, 612, 612])
torch.Size([3, 425, 640])
torch.Size([3, 640, 512])
torch.Size([3, 480, 640])
torch.Size([3, 427, 640])
torch.Size([3, 427, 640])
torch.Size([3, 416, 640])
torch.Size([3, 480, 640])
torch.Size([3, 640, 416])
torch.Size([3, 481, 640])
torch.Size([3, 573, 640])
torch.Size([3, 640, 480])
torch.Size([3, 480, 640])
torch.Size([3, 428, 640])
torch.Size([3, 640, 480])
torch.Size([3, 640, 427])
torch.Size([3, 536, 640])
torch.Size([3, 480, 640])
torch.Size([3, 428, 640])
torch.Size([3, 424, 640])


In [29]:
a = [1, 2, 3]

b = list(
    *a
)

print(b)

TypeError: list expected at most 1 argument, got 3